export const FILL_REGISTER_FORM = "FILL_REGISTER_FORM";
export const UPDATE_REGISTER_FORM = "UPDATE_REGISTER_FORM";
export const ADD_BANK_ACCOUNT = "ADD_BANK_ACCOUNT";
export const REMOVE_BANK_ACCOUNT = "REMOVE_BANK_ACCOUNT";
export const UPDATE_BANK_ACCOUNT = "UPDATE_BANK_ACCOUNT";
